# Generated by Django 4.1 on 2022-09-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('visitors', '0002_room_beds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('active', models.BooleanField()),
                ('rooms', models.ManyToManyField(related_name='reservations', to='visitors.room')),
                ('visitors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.visitor')),
            ],
        ),
    ]
