# Generated by Django 4.1 on 2022-09-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='visitors',
            new_name='visitor',
        ),
    ]
