# Generated by Django 4.1 on 2022-09-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_visitor_user'),
        ('visitors', '0004_rename_visitors_reservation_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.visitor'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')])),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visitors.reservation')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
